# Site settings
title: StaticVoid
description: 'A coding blog'
url: 'http://blog.staticvoid.co.nz'
baseurl: ''
google_analytics: 'UA-28637942-1'
disqus_shortname: 'staticvoidblog'

author:
  name: 'Luke McGregor'
  image: 'https://www.gravatar.com/avatar/46e93e55b8f4f652201516c2f7bf3323?s=256'
  twitter_username: staticv0id
  github_username:  lukemcgregor

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

paginate_multiple:
  - paginate: 10
    paginate_path: '/technical/:num/'
    sub_dir: '/technical'
  - paginate: 10
    paginate_path: '/personal/:num/'
    sub_dir: '/personal'

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems:
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-paginate-multiple

exclude: ['README.md', 'Gemfile', 'LICENSE', 'Gemfile.lock']
